var allFiles=[],filteredFiles=[],decisions={},currentPage=0,PAGE_SIZE=50,NOW=new Date();
function parseCSV(text){var lines=text.replace(/\r/g,'').trim().split('\n');if(lines.length<2)return[];var headers=lines[0].split(',').map(function(h){return h.trim().replace(/^"|"$/g,'');});var fpIdx=0,szIdx=-1,dtIdx=-1;for(var i=0;i<headers.length;i++){if(/fullpath|path|name|file/i.test(headers[i]))fpIdx=i;if(/size/i.test(headers[i]))szIdx=i;if(/access|date|modified|time/i.test(headers[i]))dtIdx=i;}var isKB=szIdx>=0&&/kb/i.test(headers[szIdx]);var files=[];for(var i=1;i<lines.length;i++){if(!lines[i])continue;var row=lines[i].split(',').map(function(c){return c.trim().replace(/^"|"$/g,'');});if(!row[fpIdx])continue;var sz=szIdx>=0?parseFloat(row[szIdx]):0;if(isNaN(sz))sz=0;if(isKB)sz=sz/1024;var dt=dtIdx>=0&&row[dtIdx]?new Date(row[dtIdx]):null;files.push({path:row[fpIdx],sizeMB:sz,lastAccessed:(dt&&!isNaN(dt))?dt:null});}return files;}
function getTopFolder(path){var parts=path.replace(/\\/g,'/').split('/').filter(Boolean);return parts.length>1?parts[1]:(parts[0]||'Unknown');}
function getAgeYears(dt){if(!dt||isNaN(dt))return null;return(NOW-dt)/(1000*60*60*24*365);}
function ageBadge(dt){var y=getAgeYears(dt);if(y===null)return'<span class="badge badge-neutral">Unknown</span>';if(y<1)return'<span class="badge badge-success">&lt;1yr</span>';if(y<2)return'<span class="badge badge-warn">1-2yr</span>';if(y<3)return'<span class="badge badge-warn">2-3yr</span>';return'<span class="badge badge-danger">3+yr</span>';}
function fmt(mb){return mb>=1024?(mb/1024).toFixed(1)+' GB':mb.toFixed(1)+' MB';}
function fmtDate(dt){return(!dt||isNaN(dt))?'—':dt.toISOString().slice(0,10);}
function buildSummary(){var totalMB=allFiles.reduce(function(s,f){return s+f.sizeMB;},0);var stale=allFiles.filter(function(f){var y=getAgeYears(f.lastAccessed);return y!==null&&y>=2;});var staleMB=stale.reduce(function(s,f){return s+f.sizeMB;},0);document.getElementById('summary-cards').innerHTML='<div class="metric-card"><div class="metric-label">Total files</div><div class="metric-value">'+allFiles.length.toLocaleString()+'</div></div>'+'<div class="metric-card"><div class="metric-label">Total size</div><div class="metric-value">'+fmt(totalMB)+'</div></div>'+'<div class="metric-card"><div class="metric-label">Stale 2yr+</div><div class="metric-value">'+stale.length.toLocaleString()+'</div><div class="metric-sub">'+fmt(staleMB)+' recoverable</div></div>'+'<div class="metric-card"><div class="metric-label">Avg file size</div><div class="metric-value">'+(allFiles.length?fmt(totalMB/allFiles.length):'—')+'</div></div>';}
function buildCharts(){var folderMap={};allFiles.forEach(function(f){var k=getTopFolder(f.path);folderMap[k]=(folderMap[k]||0)+f.sizeMB;});var topF=Object.entries(folderMap).sort(function(a,b){return b[1]-a[1];}).slice(0,8);var maxF=Math.max.apply(null,topF.map(function(x){return x[1];}));document.getElementById('folderChart').innerHTML=topF.map(function(x){var pct=Math.max((x[1]/maxF)*100,3);return'<div class="bar-col"><div class="bar-fill" style="height:'+pct+'%;background:#2a78d6;"><span class="bar-val">'+fmt(x[1])+'</span></div><div class="bar-label" title="'+x[0]+'">'+x[0]+'</div></div>';}).join('');var buckets=[0,0,0,0];allFiles.forEach(function(f){var y=getAgeYears(f.lastAccessed);if(y===null)return;if(y<1)buckets[0]++;else if(y<2)buckets[1]++;else if(y<3)buckets[2]++;else buckets[3]++;});var labels=['< 1yr','1-2yr','2-3yr','3+yr'];var colors=['#1baf7a','#b8860b','#c0392b','#7b1f15'];var maxB=Math.max.apply(null,buckets)||1;document.getElementById('ageChart').innerHTML=buckets.map(function(c,i){var pct=Math.max((c/maxB)*100,c>0?3:0);return'<div class="bar-col"><div class="bar-fill" style="height:'+pct+'%;background:'+colors[i]+';"><span class="bar-val">'+c.toLocaleString()+'</span></div><div class="bar-label">'+labels[i]+'</div></div>';}).join('');}
function buildLargest(){var top=allFiles.slice().sort(function(a,b){return b.sizeMB-a.sizeMB;}).slice(0,20);document.getElementById('largest-body').innerHTML=top.map(function(f){return'<tr><td title="'+f.path+'">'+f.path+'</td><td style="white-space:nowrap;color:var(--text-primary)">'+fmt(f.sizeMB)+'</td><td>'+fmtDate(f.lastAccessed)+'</td><td>'+ageBadge(f.lastAccessed)+'</td></tr>';}).join('');}
function buildFolderFilter(){var folders=[...new Set(allFiles.map(function(f){return getTopFolder(f.path);}))].sort();document.getElementById('folder-filter').innerHTML='<option value="">All folders</option>'+folders.map(function(f){return'<option value="'+f+'">'+f+'</option>';}).join('');}
function applyFilters(){var search=document.getElementById('search-filter').value.toLowerCase();var folder=document.getElementById('folder-filter').value;var age=document.getElementById('age-filter').value;var size=document.getElementById('size-filter').value;var dec=document.getElementById('dec-filter').value;filteredFiles=allFiles.filter(function(f){if(search&&!f.path.toLowerCase().includes(search))return false;if(folder&&getTopFolder(f.path)!==folder)return false;if(age!==''){var y=getAgeYears(f.lastAccessed);if(age==='0'&&!(y!==null&&y<1))return false;if(age==='1'&&!(y!==null&&y>=1&&y<2))return false;if(age==='2'&&!(y!==null&&y>=2&&y<3))return false;if(age==='3'&&!(y!==null&&y>=3))return false;}if(size==='large'&&f.sizeMB<100)return false;if(size==='medium'&&(f.sizeMB<10||f.sizeMB>=100))return false;if(size==='small'&&f.sizeMB>=10)return false;if(dec==='delete'&&decisions[f.path]!=='delete')return false;if(dec==='keep'&&decisions[f.path]!=='keep')return false;if(dec==='undecided'&&decisions[f.path])return false;return true;});currentPage=0;renderTable();renderSubmitBar();}
function renderTable(){var start=currentPage*PAGE_SIZE;var page=filteredFiles.slice(start,start+PAGE_SIZE);var tbody=document.getElementById('review-body');if(!page.length){tbody.innerHTML='<tr><td colspan="4" style="text-align:center;padding:2rem;color:var(--text-muted)">No files match</td></tr>';return;}tbody.innerHTML=page.map(function(f){var d=decisions[f.path];var safePath=f.path.replace(/'/g,"\\'");return'<tr><td title="'+f.path+'">'+f.path+'</td><td style="white-space:nowrap">'+fmt(f.sizeMB)+'</td><td>'+fmtDate(f.lastAccessed)+'</td><td style="text-align:center;white-space:nowrap"><button class="action-btn delete'+(d==='delete'?' active-delete':'')+'" onclick="setDecision(\''+safePath+'\',\'delete\')">Delete</button><button class="action-btn keep'+(d==='keep'?' active-keep':'')+'" onclick="setDecision(\''+safePath+'\',\'keep\')">Keep</button></td></tr>';}).join('');var total=filteredFiles.length,pages=Math.ceil(total/PAGE_SIZE);document.getElementById('pagination').innerHTML=total>PAGE_SIZE?'<span>'+(start+1).toLocaleString()+'–'+Math.min(start+PAGE_SIZE,total).toLocaleString()+' of '+total.toLocaleString()+'</span><div style="display:flex;gap:6px"><button class="btn btn-sm" onclick="changePage(-1)"'+(currentPage===0?' disabled':'')+'>← Prev</button><button class="btn btn-sm" onclick="changePage(1)"'+(currentPage>=pages-1?' disabled':'')+'>Next →</button></div>':'<span>'+total.toLocaleString()+' files</span>';}
function changePage(d){currentPage+=d;renderTable();}
function setDecision(path,action){if(decisions[path]===action)delete decisions[path];else decisions[path]=action;updateBadge();applyFilters();}
function updateBadge(){var c=Object.keys(decisions).length;var b=document.getElementById('dec-badge');b.textContent=c;b.style.display=c>0?'':'none';}
function renderSubmitBar(){var dels=Object.values(decisions).filter(function(d){return d==='delete';}).length;var keeps=Object.values(decisions).filter(function(d){return d==='keep';}).length;var total=Object.keys(decisions).length;var s=document.getElementById('submit-section');if(!total){s.innerHTML='';return;}var delMB=allFiles.filter(function(f){return decisions[f.path]==='delete';}).reduce(function(s,f){return s+f.sizeMB;},0);s.innerHTML='<div class="submit-bar"><div><div style="font-size:14px;color:var(--accent);font-weight:600;">'+total+' decisions — '+dels+' delete | '+keeps+' keep</div><div style="font-size:12px;color:var(--accent);margin-top:2px;">'+fmt(delMB)+' flagged for removal</div></div><button class="btn btn-accent" onclick="switchTab(\'decisions\',document.querySelectorAll(\'.tab\')[2])">View &amp; export →</button></div>';}
function renderDecisions(){var dels=allFiles.filter(function(f){return decisions[f.path]==='delete';});var keeps=allFiles.filter(function(f){return decisions[f.path]==='keep';});var delMB=dels.reduce(function(s,f){return s+f.sizeMB;},0);document.getElementById('dec-summary').innerHTML='<div class="grid-4"><div class="metric-card"><div class="metric-label">Delete</div><div class="metric-value" style="color:var(--danger)">'+dels.length.toLocaleString()+'</div><div class="metric-sub">'+fmt(delMB)+' to recover</div></div><div class="metric-card"><div class="metric-label">Keep</div><div class="metric-value" style="color:var(--success)">'+keeps.length.toLocaleString()+'</div></div><div class="metric-card"><div class="metric-label">Undecided</div><div class="metric-value">'+(allFiles.length-dels.length-keeps.length).toLocaleString()+'</div></div></div>';var list=[].concat(dels.map(function(f){return Object.assign({},f,{dec:'delete'});}),keeps.map(function(f){return Object.assign({},f,{dec:'keep'});}));document.getElementById('dec-list').innerHTML=list.length===0?'<div style="color:var(--text-muted);padding:1rem 0;">No decisions yet.</div>':list.slice(0,200).map(function(f){return'<div style="display:flex;justify-content:space-between;align-items:center;padding:7px 0;border-bottom:1px solid var(--border);font-size:13px;gap:12px;"><span style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;" title="'+f.path+'">'+f.path+'</span><div style="display:flex;align-items:center;gap:10px;flex-shrink:0;"><span style="font-size:12px;color:var(--text-muted);">'+fmt(f.sizeMB)+'</span><span class="badge '+(f.dec==='delete'?'badge-danger':'badge-success')+'">'+f.dec+'</span></div></div>';}).join('')+(list.length>200?'<div style="font-size:12px;color:var(--text-muted);padding:8px 0;">…and '+(list.length-200)+' more. Export CSV to see all.</div>':'');}
function exportDecisions(){var rows=[['FullPath','SizeMB','LastAccessed','Decision']];allFiles.forEach(function(f){if(decisions[f.path])rows.push(['"'+f.path+'"',f.sizeMB.toFixed(2),fmtDate(f.lastAccessed),decisions[f.path]]);});if(rows.length===1){alert('No decisions yet.');return;}var csv=rows.map(function(r){return r.join(',');}).join('\n');var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='cleanup_decisions.csv';a.click();}
function switchTab(name,el){document.querySelectorAll('.tab').forEach(function(t){t.classList.remove('active');});el.classList.add('active');['analyze','review','decisions'].forEach(function(t){document.getElementById('tab-'+t).style.display=t===name?'':'none';});if(name==='decisions')renderDecisions();}
function loadFiles(files){if(!files||!files.length){setStatus('No data found. Check your CSV has FullPath, SizeMB, LastAccessed columns.');return;}allFiles=files;filteredFiles=files.slice();document.getElementById('upload-view').style.display='none';document.getElementById('dashboard-view').style.display='';buildSummary();buildFolderFilter();applyFilters();setTimeout(function(){buildCharts();buildLargest();},50);}
function resetDashboard(){allFiles=[];filteredFiles=[];decisions={};document.getElementById('upload-view').style.display='';document.getElementById('dashboard-view').style.display='none';document.getElementById('csvInput').value='';setStatus('');}
function setStatus(msg){document.getElementById('status-msg').textContent=msg;}
function loadFromPaste(){var text=document.getElementById('pastebox').value.trim();if(!text){alert('Please paste some CSV data first.');return;}setStatus('Parsing pasted data...');setTimeout(function(){var f=parseCSV(text);if(!f.length){setStatus('Could not parse — make sure first row has column headers.');return;}loadFiles(f);},30);}
window.addEventListener('DOMContentLoaded',function(){
  document.getElementById('csvInput').addEventListener('change',function(e){var file=e.target.files[0];if(!file)return;setStatus('Reading '+file.name+' ('+( file.size/1024/1024).toFixed(1)+' MB)...');var reader=new FileReader();reader.onload=function(ev){setStatus('Parsing...');setTimeout(function(){var f=parseCSV(ev.target.result);setStatus('');loadFiles(f);},30);};reader.onerror=function(){setStatus('Error reading file. Try the paste option below.');};reader.readAsText(file);});
  var dz=document.getElementById('dropzone');
  dz.addEventListener('dragover',function(e){e.preventDefault();dz.classList.add('drag');});
  dz.addEventListener('dragleave',function(){dz.classList.remove('drag');});
  dz.addEventListener('drop',function(e){e.preventDefault();dz.classList.remove('drag');var f=e.dataTransfer.files[0];if(!f)return;setStatus('Reading '+f.name+'...');var reader=new FileReader();reader.onload=function(ev){setStatus('Parsing...');setTimeout(function(){loadFiles(parseCSV(ev.target.result));setStatus('');},30);};reader.onerror=function(){setStatus('Drop failed. Try the button or paste option.');};reader.readAsText(f);});
});
